In [1]:
import numpy as np 
import pandas as pd
import matplotlib as plt 
%matplotlib inline

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
path = ("X:\\VS_CODE\\Notebook\\DATASETS\\_Classification\\titanic\\train.csv")

In [4]:
test_path = ("X:\\VS_CODE\\Notebook\\DATASETS\\_Classification\\titanic\\test.csv")

In [5]:
y_test = ("X:\\VS_CODE\\Notebook\\DATASETS\\_Classification\\titanic\\gender_submission.csv")

In [6]:
y_test_data = pd.read_csv(y_test)

In [7]:
data = pd.read_csv(path)

In [8]:
test_data = pd.read_csv(test_path)

In [9]:
test_data.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [10]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [11]:
y_test_data  = y_test_data.drop(["PassengerId"], axis=1)
y_test_data.head()

Survived
0         0
1         1
2         0
3         0
4         1

In [12]:
y_test_data = y_test_data['Survived']
y_test_data

0      0
1      1
2      0
3      0
4      1
      ..
413    0
414    1
415    0
416    0
417    0
Name: Survived, Length: 418, dtype: int64

In [13]:
y_data = data['Survived']
y_data.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [14]:
y = pd.concat([y_data, y_test_data])

In [15]:
data = data.drop(['Survived'], axis = 1)

In [16]:
data

PassengerId  Pclass                                               Name  \
0              1       3                            Braund, Mr. Owen Harris   
1              2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2              3       3                             Heikkinen, Miss. Laina   
3              4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4              5       3                           Allen, Mr. William Henry   
..           ...     ...                                                ...   
886          887       2                              Montvila, Rev. Juozas   
887          888       1                       Graham, Miss. Margaret Edith   
888          889       3           Johnston, Miss. Catherine Helen "Carrie"   
889          890       1                              Behr, Mr. Karl Howell   
890          891       3                                Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S  
1    female  38.0      1      0          PC 17599  71.2833   C85        C  
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3    female  35.0      1      0            113803  53.1000  C123        S  
4      male  35.0      0      0            373450   8.0500   NaN        S  
..      ...   ...    ...    ...               ...      ...   ...      ...  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q  

[891 rows x 11 columns]

In [17]:
df = pd.concat([data, test_data] )

In [18]:
df

PassengerId  Pclass                                               Name  \
0              1       3                            Braund, Mr. Owen Harris   
1              2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2              3       3                             Heikkinen, Miss. Laina   
3              4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4              5       3                           Allen, Mr. William Henry   
..           ...     ...                                                ...   
413         1305       3                                 Spector, Mr. Woolf   
414         1306       1                       Oliva y Ocana, Dona. Fermina   
415         1307       3                       Saether, Mr. Simon Sivertsen   
416         1308       3                                Ware, Mr. Frederick   
417         1309       3                           Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  22.0      1      0           A/5 21171    7.2500   NaN        S  
1    female  38.0      1      0            PC 17599   71.2833   C85        C  
2    female  26.0      0      0    STON/O2. 3101282    7.9250   NaN        S  
3    female  35.0      1      0              113803   53.1000  C123        S  
4      male  35.0      0      0              373450    8.0500   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[1309 rows x 11 columns]

In [19]:
y

0      0
1      1
2      1
3      1
4      0
      ..
413    0
414    1
415    0
416    0
417    0
Name: Survived, Length: 1309, dtype: int64

In [20]:
cols = ['Name','Ticket','Cabin', 'PassengerId']

In [21]:
X = df.drop(cols, axis=1)

In [22]:
X['Embarked'].isnull().value_counts()

Embarked
False    1307
True        2
Name: count, dtype: int64

In [23]:
X['Age'].isnull().value_counts()

Age
False    1046
True      263
Name: count, dtype: int64

In [24]:
X.isnull().any()

Pclass      False
Sex         False
Age          True
SibSp       False
Parch       False
Fare         True
Embarked     True
dtype: bool

In [25]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.impute import KNNImputer

In [26]:
def random_sampling_imputation(df, column):
    # Get non-null values from the column
    non_null_values = df[column].dropna().values
    
    # Count null values
    null_count = df[column].isnull().sum()
    
    # Randomly sample from non-null values
    random_sample = np.random.choice(non_null_values, size=null_count, replace=True)
    
    # Create a copy of the original column
    imputed_column = df[column].copy()
    
    # Fill null values with the random sample
    imputed_column.loc[imputed_column.isnull()] = random_sample
    
    return imputed_column

In [27]:
X['journey'] = random_sampling_imputation(X, 'Embarked')

In [28]:
X = X.drop(['Embarked'], axis=1)

In [29]:
X.isnull().any()

Pclass     False
Sex        False
Age         True
SibSp      False
Parch      False
Fare        True
journey    False
dtype: bool

In [30]:
imputer = SimpleImputer()
X['age'] = imputer.fit_transform(X[['Age']])

In [31]:
imputer = SimpleImputer()
X['Price'] = imputer.fit_transform(X[['Fare']])

In [32]:
X = X.drop(["Fare"], axis=1)

In [33]:
X = X.drop(["Age"], axis=1)

In [34]:
X.isnull().any()

Pclass     False
Sex        False
SibSp      False
Parch      False
journey    False
age        False
Price      False
dtype: bool

In [35]:
journey_column = X[['journey']]  # Make sure to use double brackets to create a DataFrame

# Perform one-hot encoding
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
encoded_journey = ohe.fit_transform(journey_column)

# Create new column names
new_column_names = [f'Journey_{cat}' for cat in ohe.categories_[0]]

# Create a new DataFrame with the encoded values
encoded_df = pd.DataFrame(encoded_journey, columns=new_column_names, index=X.index)

# Concatenate the new columns to the original DataFrame
X = pd.concat([X, encoded_df], axis=1)

In [36]:
X = X.drop(['journey'], axis = 1)

In [37]:
gender = X[['Sex']]

In [38]:
encoded_gender = ohe.fit_transform(gender)
new_column = [f'Gender_{cat}' for cat in ohe.categories_[0]]
new_df = pd.DataFrame(encoded_gender, columns=new_column, index = X.index)
X = pd.concat([X, new_df], axis=1)

In [39]:
X = X.drop(['Sex'], axis = 1)

In [40]:
X

Pclass  SibSp  Parch        age     Price  Journey_C  Journey_Q  \
0         3      1      0  22.000000    7.2500        0.0        0.0   
1         1      1      0  38.000000   71.2833        1.0        0.0   
2         3      0      0  26.000000    7.9250        0.0        0.0   
3         1      1      0  35.000000   53.1000        0.0        0.0   
4         3      0      0  35.000000    8.0500        0.0        0.0   
..      ...    ...    ...        ...       ...        ...        ...   
413       3      0      0  29.881138    8.0500        0.0        0.0   
414       1      0      0  39.000000  108.9000        1.0        0.0   
415       3      0      0  38.500000    7.2500        0.0        0.0   
416       3      0      0  29.881138    8.0500        0.0        0.0   
417       3      1      1  29.881138   22.3583        1.0        0.0   

     Journey_S  Gender_female  Gender_male  
0          1.0            0.0          1.0  
1          0.0            1.0          0.0  
2          1.0            1.0          0.0  
3          1.0            1.0          0.0  
4          1.0            0.0          1.0  
..         ...            ...          ...  
413        1.0            0.0          1.0  
414        0.0            1.0          0.0  
415        1.0            0.0          1.0  
416        1.0            0.0          1.0  
417        0.0            0.0          1.0  

[1309 rows x 10 columns]

In [41]:
X.isnull().any()

Pclass           False
SibSp            False
Parch            False
age              False
Price            False
Journey_C        False
Journey_Q        False
Journey_S        False
Gender_female    False
Gender_male      False
dtype: bool

In [42]:
y

0      0
1      1
2      1
3      1
4      0
      ..
413    0
414    1
415    0
416    0
417    0
Name: Survived, Length: 1309, dtype: int64

In [43]:
print("Original shape of y:", y.shape)


Original shape of y: (1309,)


In [44]:
y = y.values

In [45]:
print("Original shape of y:", y.shape)


Original shape of y: (1309,)


In [46]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

## svm

In [47]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.decomposition import PCA

In [48]:
from sklearn import svm
clf = make_pipeline(PCA(n_components=7),StandardScaler(), svm.SVC(decision_function_shape='ovo'))
clf.fit(X_train, y_train)

Pipeline(steps=[('pca', PCA(n_components=7)),
                ('standardscaler', StandardScaler()),
                ('svc', SVC(decision_function_shape='ovo'))])

In [49]:
y_pred = clf.predict(X_test)

In [50]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[240,  29],
       [ 28, 135]])

In [51]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.8680555555555556

In [52]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred)
precision

np.float64(0.823170731707317)

In [53]:
from sklearn.metrics import recall_score
recall = recall_score(y_test, y_pred)
recall

np.float64(0.8282208588957055)

In [54]:
from sklearn.metrics import f1_score
f1 = f1_score(y_test, y_pred)
f1

np.float64(0.8256880733944955)

##  XGBClassifier

In [55]:
from xgboost import XGBClassifier

In [56]:
xgb = make_pipeline(StandardScaler(),XGBClassifier())
xgb.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('xgbclassifier',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric=None,
                               feature_types=None, gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, random_state=None, ...))])

In [57]:
xgb_pred = xgb.predict(X_test)

In [58]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, xgb_pred)
cm

array([[236,  33],
       [ 30, 133]])

In [59]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, xgb_pred)
accuracy

0.8541666666666666

In [60]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, xgb_pred)
precision

np.float64(0.8012048192771084)

In [61]:
from sklearn.metrics import recall_score
recall = recall_score(y_test, xgb_pred)
recall

np.float64(0.8159509202453987)

In [62]:
from sklearn.metrics import f1_score
f1 = f1_score(y_test, xgb_pred)
f1

np.float64(0.8085106382978723)

##  RandomForestClassifier

In [63]:
from sklearn.ensemble import RandomForestClassifier
rf = make_pipeline(StandardScaler(),RandomForestClassifier())

In [64]:
rf.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('randomforestclassifier', RandomForestClassifier())])

In [65]:
rf_pred = rf.predict(X_test)

In [66]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, rf_pred)
cm

array([[231,  38],
       [ 28, 135]])

In [67]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, rf_pred)
precision

np.float64(0.7803468208092486)

In [68]:
from sklearn.metrics import recall_score
recall = recall_score(y_test, rf_pred)
recall

np.float64(0.8282208588957055)

In [69]:
from sklearn.metrics import f1_score
f1 = f1_score(y_test, rf_pred)
f1

np.float64(0.8035714285714286)

## KNeighborsClassifier

In [70]:
from sklearn.neighbors import KNeighborsClassifier
neigh = make_pipeline(StandardScaler(),KNeighborsClassifier(n_neighbors=3))
neigh.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('kneighborsclassifier', KNeighborsClassifier(n_neighbors=3))])

In [71]:
neigh_pred = neigh.predict(X_test)

In [72]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, neigh_pred)
cm

array([[230,  39],
       [ 27, 136]])

In [73]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, neigh_pred)
precision

np.float64(0.7771428571428571)

In [74]:
from sklearn.metrics import recall_score
recall = recall_score(y_test, neigh_pred)
recall

np.float64(0.8343558282208589)

In [75]:
from sklearn.metrics import f1_score
f1 = f1_score(y_test, neigh_pred)
f1

np.float64(0.8047337278106509)

## logistic Reg

In [76]:
from sklearn.linear_model import LogisticRegression

In [77]:
lr = make_pipeline(StandardScaler(), LogisticRegression(random_state=42,max_iter=1000))
lr.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression',
                 LogisticRegression(max_iter=1000, random_state=42))])

In [78]:
lr_pred  = lr.predict(X_test)

In [79]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, lr_pred)
cm

array([[238,  31],
       [ 30, 133]])

In [80]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, lr_pred)
precision

np.float64(0.8109756097560976)

In [81]:
from sklearn.metrics import recall_score
recall = recall_score(y_test, lr_pred)
recall

np.float64(0.8159509202453987)

In [82]:
from sklearn.metrics import f1_score
f1 = f1_score(y_test, lr_pred)
f1

np.float64(0.8134556574923547)

###  SGD

In [83]:
from sklearn.linear_model import SGDClassifier
sgd = make_pipeline(StandardScaler(),SGDClassifier())
sgd.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('sgdclassifier', SGDClassifier())])

In [84]:
sgd_pred  = sgd.predict(X_test)

In [85]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, sgd_pred )
cm

array([[208,  61],
       [ 60, 103]])

In [86]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, sgd_pred )
precision

np.float64(0.6280487804878049)

In [87]:
from sklearn.metrics import recall_score
recall = recall_score(y_test, sgd_pred )
recall

np.float64(0.6319018404907976)

In [88]:
from sklearn.metrics import f1_score
f1 = f1_score(y_test, sgd_pred )
f1

np.float64(0.6299694189602446)